services:
  - type: web
    name: nhk-news-scraper
    env: node
    buildCommand: "npm install"
    startCommand: "node nhk_scraper.js"
    plan: free
    region: oregon
    # runtime や nodeVersion は不要・削除！
